# Generated by Django 4.0.2 on 2022-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('user_string', models.CharField(default='unknown_user', max_length=100)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
