# Generated by Django 4.0.2 on 2022-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='uuid',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
